name: Build VCC Listing

on:
  push:
    branches: [ main ]
    paths:
      - 'source.json'
      - 'VRChatImmersiveScaler/package.json'
      - '.github/workflows/release.yml'
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-listing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Fetch existing index.json from gh-pages
        run: |
          # Try to fetch existing index.json from gh-pages branch
          if git ls-remote --heads origin gh-pages | grep gh-pages; then
            git fetch origin gh-pages
            if git show origin/gh-pages:index.json > /dev/null 2>&1; then
              git show origin/gh-pages:index.json > index.json
              echo "Fetched existing index.json from gh-pages"
            else
              echo "No existing index.json found in gh-pages"
            fi
          else
            echo "No gh-pages branch exists yet"
          fi

      - name: Build VPM Listing
        run: node scripts/build-index.js

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Create a temporary directory for gh-pages
          mkdir gh-pages-deploy
          cp index.json gh-pages-deploy/
          touch gh-pages-deploy/.nojekyll
          
          # Remove any existing index.json to avoid conflicts
          rm -f index.json
          
          # Check if gh-pages branch exists
          if git ls-remote --heads origin gh-pages | grep gh-pages; then
            git fetch origin gh-pages
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf .
          fi
          
          # Copy the new files
          cp gh-pages-deploy/index.json .
          cp gh-pages-deploy/.nojekyll .
          # Preserve install.html if it exists
          [ -f install.html ] && cp install.html gh-pages-deploy/
          
          # Restore install.html if it was preserved
          [ -f gh-pages-deploy/install.html ] && cp gh-pages-deploy/install.html .
          
          # Commit and push
          git add index.json .nojekyll install.html
          git commit -m "Update VCC listing" || echo "No changes to commit"
          git push origin gh-pages

  build-package:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Unity Package
        id: create_package
        run: |
          # Create package directory structure
          mkdir -p package
          cp -r VRChatImmersiveScaler/* package/
          
          # Read version and name from package.json
          VERSION=$(cat VRChatImmersiveScaler/package.json | grep '"version"' | head -1 | cut -d '"' -f 4)
          PACKAGE_NAME=$(cat VRChatImmersiveScaler/package.json | grep '"name"' | head -1 | cut -d '"' -f 4)
          
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "PACKAGE_NAME=${PACKAGE_NAME}" >> $GITHUB_OUTPUT
          echo "FILENAME=${PACKAGE_NAME}-${VERSION}.zip" >> $GITHUB_OUTPUT
          
          # Create zip file
          cd package
          zip -r "../${PACKAGE_NAME}-${VERSION}.zip" .
          cd ..
          
          echo "Created package: ${PACKAGE_NAME}-${VERSION}.zip"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.create_package.outputs.FILENAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}