name: Build VCC Listing

on:
  push:
    branches: [ main ]
    paths:
      - 'source.json'
      - 'VRChatImmersiveScaler/package.json'
      - '.github/workflows/release.yml'
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-listing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build VPM Listing
        run: |
          # Create index.json from source.json
          node -e "
          const fs = require('fs');
          const path = require('path');
          
          // Read source.json
          const source = JSON.parse(fs.readFileSync('source.json', 'utf8'));
          
          // Read package.json
          const packageJson = JSON.parse(fs.readFileSync('VRChatImmersiveScaler/package.json', 'utf8'));
          
          // Create the listing structure
          const listing = {
            name: source.name,
            id: source.id,
            url: source.url,
            author: source.author,
            description: source.description,
            infoLink: source.infoLink,
            bannerUrl: source.bannerUrl,
            packages: {
              [packageJson.name]: {
                versions: {
                  [packageJson.version]: {
                    ...packageJson,
                    url: \`https://github.com/\${process.env.GITHUB_REPOSITORY}/releases/download/v\${packageJson.version}/\${packageJson.name}-\${packageJson.version}.zip\`
                  }
                }
              }
            }
          };
          
          // Write index.json
          fs.writeFileSync('index.json', JSON.stringify(listing, null, 2));
          console.log('Generated index.json');
          "

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  build-package:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Unity Package
        run: |
          # Create package directory structure
          mkdir -p package
          cp -r VRChatImmersiveScaler/* package/
          
          # Read version from package.json
          VERSION=$(cat VRChatImmersiveScaler/package.json | grep '"version"' | cut -d '"' -f 4)
          PACKAGE_NAME=$(cat VRChatImmersiveScaler/package.json | grep '"name"' | cut -d '"' -f 4)
          
          # Create zip file
          cd package
          zip -r "../${PACKAGE_NAME}-${VERSION}.zip" .
          cd ..

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.PACKAGE_NAME }}-${{ env.VERSION }}.zip
          asset_name: ${{ env.PACKAGE_NAME }}-${{ env.VERSION }}.zip
          asset_content_type: application/zip